SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS User;

CREATE TABLE User(
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name varchar(50) NOT NULL,
  Surname varchar(50) NOT NULL,
  Email varchar(255) NOT NULL,
  Password varchar(255) NOT NULL,
  Birthdate DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Ingredient;

CREATE TABLE Ingredient(
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  Name varchar(50) NOT NULL,
  GramsProduct FLOAT NOT NULL,
  GramsCarbs FLOAT NOT NULL,
  PRIMARY KEY (Id, UserId),
  FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Recipe;

CREATE TABLE Recipe(
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  Name varchar(50) NOT NULL,
  PRIMARY KEY (Id, UserId),
  FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS Contains;

CREATE TABLE Contains(
  RecipeId INT NOT NULL,
  IngredientId INT NOT NULL,
  GramsIngredient FLOAT NOT NULL,
  Units FLOAT NOT NULL,
  Pieces INT NOT NULL,
  PRIMARY KEY (RecipeId,IngredientId),
  FOREIGN KEY (RecipeId) REFERENCES Recipe(Id) ON DELETE CASCADE,
  FOREIGN KEY (IngredientId) REFERENCES Ingredient(Id) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;